services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackframe
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - 2500:2500
      - 9000:9000
      - 1100:1100
    volumes:
      - inbucket-data:/data

volumes:
  postgres-data:
  inbucket-data:

