services:
  # ================= stack =================

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stackframe
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - 2500:2500
      - 8105:9000
      - 1100:1100
    volumes:
      - inbucket-data:/data

  # ================= svix =================

  svix-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: svix
    volumes:
      - svix-postgres-data:/var/lib/postgresql/data
    
  svix-redis:
    image: docker.io/redis:7-alpine
    command: --save 60 500 --appendonly yes --appendfsync everysec
    volumes:
      - svix-redis-data:/data

  svix-server:
    image: svix/svix-server
    environment:
      WAIT_FOR: 'true'
      SVIX_REDIS_DSN: redis://svix-redis:6379
      SVIX_DB_DSN: postgres://postgres:password@svix-db:5432/svix
      SVIX_CACHE_TYPE: memory
      SVIX_JWT_SECRET: secret
      SVIX_LOG_LEVEL: trace
      SVIX_QUEUE_TYPE: redis
    ports:
      - 8113:8071
    depends_on:
    - svix-redis
    - svix-db

# ================= volumes =================

volumes:
  postgres-data:
  inbucket-data:
  svix-redis-data:
  svix-postgres-data:

