name: Mirror main branch to main-mirror-for-wdb

on:
  push:
    branches:
      - main

jobs:
  lint_and_build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Mirror branch
        run: |
          git pull --all
          git switch -c main-mirror-for-wdb
          git reset --hard origin/main

      - name: Push branch
        run: |
          git push origin main-mirror-for-wdb
